using FlowOps.Domain.Attention;
using FlowOps.Domain.Sla;
using FlowOps.Domain.Tickets;

namespace FlowOps.Application.Tickets;

/// <summary>
/// The derived SLA view of a ticket (SLA-RULE-10) — computed by <see cref="SlaPolicy.GetStatus"/>
/// on every read and never persisted (docs/database.md §13).
/// </summary>
/// <param name="Status">The derived status. Not a column, not a cache.</param>
/// <param name="DueAt">The stored deadline, already adjusted for any accrued pause.</param>
/// <param name="TargetMinutes">The target captured on the ticket when its clock started (SLA-RULE-03).</param>
/// <param name="PausedMinutes">Pending time accrued so far and excluded from elapsed (SLA-RULE-07).</param>
/// <param name="Remaining">
/// Time left until <paramref name="DueAt"/>; negative once the deadline has passed, so a caller can
/// render "42m left" or "2h 14m over" from one value. Null for a terminal ticket, whose outcome is
/// the persisted <c>SlaMet</c> fact rather than a countdown.
/// </param>
public sealed record TicketSlaView(
    SlaStatus Status,
    DateTimeOffset DueAt,
    int TargetMinutes,
    int PausedMinutes,
    TimeSpan? Remaining);

/// <summary>
/// Read-side shapes for the Phase 5 slice. EF entities never cross into Web (CLAUDE.md §11.2):
/// every query projects straight into these with <c>Select</c>, so no <see cref="Ticket"/>
/// instance is ever handed to a Razor Page.
/// </summary>
/// <remarks>
/// <c>Reference</c> is non-nullable here even though <see cref="Ticket.Reference"/> is
/// <c>string?</c>: the column is NOT NULL and generated by PostgreSQL's sequence default, so any
/// persisted row always has one. The nullability on the aggregate only describes the brief
/// pre-INSERT window, which no read path can observe.
/// </remarks>
/// <summary>
/// A closed, named set of work-queue filters (Phase 10) — deliberately not a generic
/// filter/search framework. Each value corresponds to exactly one dashboard KPI's "clickable
/// through to the filtered work it represents" (CLAUDE.md §22), so the set only grows if a future
/// KPI needs a new one; it is not meant to become a general query-builder.
/// </summary>
public enum TicketQueueFilter
{
    /// <summary>No filter — the plain work queue, unchanged from Phase 5.</summary>
    None,

    /// <summary>The "Open Work" KPI: <c>Status NOT IN (Resolved, Closed)</c>.</summary>
    OpenWork,

    /// <summary>The "Overdue" KPI: <c>DueDate &lt; now</c> and not terminal. Deliberately the
    /// <see cref="FlowOps.Domain.Attention.AttentionSignalCode.Overdue"/> definition, never SLA
    /// breach — the two are different fields (<c>DueDate</c> vs <c>SlaDueAt</c>).</summary>
    Overdue,

    /// <summary>The "SLA Compliance" and "Average Resolution Time" KPIs share this filter: both
    /// are computed over the same population — tickets whose <c>ResolvedAt</c> falls in the
    /// 90-day reporting window (see <see cref="AnalyticsQueryService"/>).</summary>
    ResolvedRecently,
}

public sealed record TicketListItem(
    int Id,
    string Reference,
    string Title,
    WorkType WorkType,
    Priority Priority,
    Status Status,
    string TeamName,
    string CategoryName,
    string? AssigneeDisplayName,
    DateTimeOffset CreatedAt,
    TicketSlaView Sla);

/// <summary>
/// One attention signal, flattened for display. Carries the Domain's own code and severity so the
/// page can order and label without re-deciding anything, but is an Application record rather than
/// the Domain <see cref="AttentionSignal"/> itself, keeping Domain types out of Web.
/// </summary>
public sealed record AttentionSignalView(
    AttentionSignalCode Code,
    AttentionSeverity Severity,
    string Headline);

/// <summary>
/// A ticket that needs attention, with the signals <see cref="AttentionPolicy"/> found for it.
/// The list arrives already ranked by <see cref="AttentionPolicy.Rank"/> (ATTN-RULE-04) — the page
/// renders the given order and applies no ordering of its own.
/// </summary>
public sealed record AttentionListItem(
    int Id,
    string Reference,
    string Title,
    Priority Priority,
    Status Status,
    string TeamName,
    string? AssigneeDisplayName,
    TicketSlaView Sla,
    IReadOnlyList<AttentionSignalView> Signals)
{
    /// <summary>The most severe signal on this ticket — what put it where it is in the ranking.</summary>
    public AttentionSeverity HighestSeverity => Signals.Max(s => s.Severity);
}

/// <summary>Ticket detail for the ticket detail page.</summary>
/// <remarks>
/// <c>TeamId</c>, <c>RequesterId</c> and <c>AssigneeId</c> accompany their display names because
/// the page must rebuild a <see cref="TicketAuthorizationSnapshot"/> to ask
/// <see cref="TicketAccessPolicy"/> which workflow actions to offer. They are the policy's inputs,
/// not decorations — display names cannot answer "is the caller the assignee".
/// </remarks>
public sealed record TicketDetail(
    int Id,
    string Reference,
    string Title,
    string Description,
    WorkType WorkType,
    Priority Priority,
    Status Status,
    int TeamId,
    string TeamName,
    string CategoryName,
    string? ProjectName,
    Guid RequesterId,
    string RequesterDisplayName,
    Guid? AssigneeId,
    string? AssigneeDisplayName,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    DateTimeOffset? DueDate,
    TicketSlaView Sla);

/// <summary>
/// Which source table a <see cref="TicketTimelineEntry"/> was projected from. A presentation-layer
/// distinction only — it exists to disambiguate the merged timeline's two id sequences (an event
/// id and a comment id are not comparable) and to tell the view which fields are populated. It is
/// not a business rule: AUDIT-RULE-06 requires events and comments to stay stored and queried
/// separately and to merge only for display, and this enum is how that merge is represented.
/// </summary>
public enum TicketTimelineEntryKind
{
    /// <summary>Ordered before <see cref="Comment"/> as this type's tiebreak default — an
    /// arbitrary but fixed choice, not a documented rule.</summary>
    Event,
    Comment,
}

/// <summary>
/// One row of a ticket's merged activity timeline (AUDIT-RULE-06): either a <c>TicketEvent</c>
/// (audit, AUDIT-RULE-01/02) or a <c>TicketComment</c> (human operational content, TICKET-ENT-05),
/// flattened into one explicit shape rather than exposed as two entity types or as <c>object</c>.
/// Event-only and comment-only fields are populated according to <see cref="Kind"/>; the two
/// source tables remain distinct entities and distinct queries — only this presentation record
/// merges them.
/// </summary>
/// <param name="Id">The source row's own id. Not unique across kinds — always pair with
/// <see cref="Kind"/> when identifying an entry (e.g. as a Razor <c>@key</c>).</param>
/// <param name="OccurredAt">The event's <c>OccurredAt</c> or the comment's <c>CreatedAt</c> —
/// the timeline's primary ordering key.</param>
/// <param name="EventType">Set only when <see cref="Kind"/> is <see cref="TicketTimelineEntryKind.Event"/>.</param>
/// <param name="Field">Set only for field-change events.</param>
/// <param name="Body">Set only when <see cref="Kind"/> is <see cref="TicketTimelineEntryKind.Comment"/>.</param>
/// <param name="IsInternal">Set only for comments (TICKET-ENT-05). Never <c>true</c> in a result
/// handed to a caller <see cref="TicketAccessPolicy.CanSeeInternalComments"/> denies — that
/// exclusion happens in the query that builds this list, not here.</param>
public sealed record TicketTimelineEntry(
    TicketTimelineEntryKind Kind,
    int Id,
    DateTimeOffset OccurredAt,
    string ActorDisplayName,
    TicketEventType? EventType,
    string? Field,
    string? OldValue,
    string? NewValue,
    string? Note,
    string? Body,
    bool? IsInternal);

/// <summary>
/// One page of results plus the totals a pager needs. <paramref name="TotalCount"/> is the count
/// of rows the caller is authorized to see, not the table total — the same authorization scope is
/// applied to the count query as to the page query.
/// </summary>
public sealed record PagedResult<T>(IReadOnlyList<T> Items, int PageNumber, int PageSize, int TotalCount)
{
    public int TotalPages => TotalCount == 0 ? 1 : (int)Math.Ceiling(TotalCount / (double)PageSize);

    public bool HasPreviousPage => PageNumber > 1;

    public bool HasNextPage => PageNumber < TotalPages;
}

/// <summary>
/// The caller-supplied half of a ticket creation. Deliberately excludes every server-owned value
/// — requester, reference, timestamps, status, and all SLA fields are resolved by
/// <see cref="TicketService"/> from the authenticated user, the clock, and configuration, never
/// from the request (CLAUDE.md §12).
/// </summary>
public sealed record CreateTicketRequest(
    string Title,
    string Description,
    WorkType WorkType,
    Priority Priority,
    int TeamId,
    int CategoryId,
    int? ProjectId);

/// <summary>
/// Phase 11: one category a caller may file a ticket against, grouped under its owning
/// <see cref="TeamOption"/> — the existing TICKET-INV-02 "category belongs to a team" relationship,
/// not a new one.
/// </summary>
public sealed record CategoryOption(int CategoryId, string CategoryName);

/// <summary>One team a caller may file a ticket against, with the categories that belong to it.</summary>
public sealed record TeamOption(int TeamId, string TeamName, IReadOnlyList<CategoryOption> Categories);

/// <summary>One project a caller may optionally associate a ticket with, scoped to their own
/// organization exactly like <see cref="TicketService.CreateAsync"/>'s own ProjectId check.</summary>
public sealed record ProjectOption(int ProjectId, string ProjectName);

/// <summary>
/// The options a ticket-creation form needs to populate its Team/Category/Project controls —
/// reference data only, resolved once per page load. This is a UI convenience, not a new
/// authorization boundary: it never replaces <see cref="TicketAccessPolicy.CanCreate"/>,
/// TICKET-INV-02, or the Project organization check, all of which still run, unchanged, inside
/// <see cref="TicketService.CreateAsync"/> regardless of what this list contains.
/// </summary>
public sealed record TicketCreationOptions(IReadOnlyList<TeamOption> Teams, IReadOnlyList<ProjectOption> Projects);

/// <summary>An active member of a ticket's team, offered as an "assign to" choice on Ticket
/// Details — see <see cref="TicketQueryService.GetAssignableTeamMembersAsync"/>.</summary>
public sealed record AssignableMember(Guid UserId, string DisplayName);

/// <summary>
/// SLA Compliance (CLAUDE.md §22), computed over the 90-day reporting window. Counts the
/// persisted <see cref="Ticket.SlaMet"/> fact directly (SLA-RULE-08) — this is aggregation of an
/// already-decided outcome, not a re-derivation of SLA status, so it does not duplicate
/// <see cref="SlaPolicy"/>.
/// </summary>
/// <param name="MetCount">Qualifying tickets where <c>SlaMet == true</c>.</param>
/// <param name="QualifyingCount">All qualifying tickets — resolved in the window, with a
/// non-null <c>SlaMet</c> (a reopened-and-not-yet-resolved-again ticket has neither and does not
/// count here — SLA-RULE-09 intentionally does not preserve a prior cycle's outcome).</param>
public sealed record SlaComplianceSummary(int MetCount, int QualifyingCount)
{
    /// <summary>Null — not <c>0</c>, not <c>NaN</c> — when no ticket qualifies. An honest
    /// "no data yet" rather than a fabricated percentage (CLAUDE.md §21.9's review checklist).</summary>
    public double? Percentage => QualifyingCount == 0 ? null : 100.0 * MetCount / QualifyingCount;
}

/// <summary>
/// Average Resolution Time (CLAUDE.md §22): the mean of <c>ResolvedAt − SlaStartedAt</c> over
/// tickets resolved in the 90-day window. <c>SlaStartedAt</c>, not <c>CreatedAt</c>, so a
/// reopened ticket's average reflects only its current cycle — consistent with every other
/// SLA-adjacent calculation in the system already being cycle-scoped (SLA-RULE-03/07/09), and
/// with the fact that <c>CreatedAt</c> would otherwise silently fold a prior, already-measured
/// cycle's duration into a number meant to describe only the latest one.
/// </summary>
/// <param name="Average">Null when <paramref name="SampleCount"/> is zero.</param>
public sealed record ResolutionTimeSummary(TimeSpan? Average, int SampleCount);

/// <summary>
/// One row of the current workload distribution (§3.3, "Analytics... owns... workload"; §1,
/// "Who on my team is overloaded?"): how many currently open tickets sit with one assignee (or
/// unassigned) on one team, within the caller's <see cref="AnalyticsScope"/>. Deliberately just a
/// count, not the optional ATTN-RULE-07 weighted score (not built in Phase 10).
/// </summary>
public sealed record WorkloadItem(
    int TeamId,
    string TeamName,
    Guid? AssigneeId,
    string? AssigneeDisplayName,
    int OpenTicketCount);

/// <summary>
/// The Phase 10 dashboard's exactly-four KPIs (CLAUDE.md §22) plus the workload distribution.
/// "KPIs are limited to Open Work, Overdue, SLA Compliance, Average Resolution Time" — no
/// additional vanity counter belongs here, whatever seems informative in isolation. Phase 20 adds
/// further sections *beyond* this KPI strip (trend/status/team/SLA/resolution breakdowns) — this
/// record itself, and the four KPIs it carries, are unchanged.
/// </summary>
public sealed record DashboardSummary(
    int OpenWorkCount,
    int OverdueCount,
    SlaComplianceSummary SlaCompliance,
    ResolutionTimeSummary AverageResolutionTime,
    IReadOnlyList<WorkloadItem> Workload);

/// <summary>
/// Phase 20: the dashboard's own filter state — a closed, small set of operational controls, never
/// a general query-builder. <see cref="RangeDays"/> bounds every date-scoped section (see each
/// query method's own doc comment for exactly which date column it filters); <see cref="TeamId"/>
/// and <see cref="WorkType"/> narrow every section uniformly. Never trusted as authorization: every
/// consumer applies <see cref="AnalyticsQueryService"/>'s existing organization/role scope *first*,
/// then this filter on top — a caller-supplied <see cref="TeamId"/> outside that scope simply
/// yields empty results, never a leak (see ADR-0019).
/// </summary>
public sealed record DashboardFilter(int RangeDays, int? TeamId, WorkType? WorkType)
{
    /// <summary>The only selectable range lengths — Step 7's "small set of useful ranges," not
    /// an arbitrary date picker.</summary>
    public static readonly IReadOnlyList<int> AllowedRangeDays = [30, 90, 180];

    public static readonly DashboardFilter Default = new(90, null, null);

    /// <summary>Coerces an arbitrary requested range onto the closest allowed value, and never
    /// throws on a malformed request — the dashboard degrades to the default rather than erroring.</summary>
    public static DashboardFilter From(int? rangeDays, int? teamId, WorkType? workType)
    {
        var range = rangeDays.HasValue && AllowedRangeDays.Contains(rangeDays.Value) ? rangeDays.Value : Default.RangeDays;
        return new DashboardFilter(range, teamId, workType);
    }
}

/// <summary>One team the dashboard filter bar may offer — deliberately just an id and a name, the
/// same minimal shape <see cref="TeamOption"/> uses for ticket creation.</summary>
public sealed record DashboardFilterTeamOption(int TeamId, string TeamName);

/// <summary>Phase 20 §3: one bucket of the ticket-volume trend line — a count of tickets *created*
/// within one period (a day or a week, depending on the selected range; see
/// <see cref="AnalyticsQueryService.GetTicketVolumeTrendAsync"/>). Every period in the requested
/// range appears exactly once, including zero-count periods, so the line is never misleadingly
/// discontinuous.</summary>
public sealed record DashboardTrendPoint(DateOnly PeriodStart, int Count);

/// <summary>Phase 20 §4: how many tickets *currently* hold each <see cref="Status"/>, among those
/// created within the selected range. Every status appears, including zero counts, in the
/// workflow's own declaration order (open → closed) rather than sorted by count.</summary>
public sealed record DashboardStatusCount(Status Status, int Count);

/// <summary>Phase 20 §5: one team's current open workload — a present-tense snapshot, deliberately
/// not scoped by the dashboard's date-range filter (see
/// <see cref="AnalyticsQueryService.GetTeamWorkloadBreakdownAsync"/> for why "who is carrying the
/// work right now" is not a question a creation-date window can answer).</summary>
public sealed record DashboardTeamWorkload(int TeamId, string TeamName, int OpenTicketCount);

/// <summary>
/// Phase 20 §6: every ticket created within the selected range, classified by
/// <see cref="Domain.Sla.SlaPolicy.GetStatus"/> — the same, single SLA-status authority every other
/// SLA-aware read path already uses (never re-derived). All five real <see cref="Domain.Sla.SlaStatus"/>
/// values are reported distinctly, rather than the caller collapsing them into a lossy three-way
/// "good/at-risk/bad" split — <see cref="MetCount"/> (resolved, on time) and
/// <see cref="WithinCount"/> (still open, on track) are different facts, and so is
/// <see cref="PausedCount"/> (on hold, so neither on nor off track).
/// </summary>
public sealed record DashboardSlaBreakdown(int MetCount, int WithinCount, int PausedCount, int AtRiskCount, int BreachedCount)
{
    public int Total => MetCount + WithinCount + PausedCount + AtRiskCount + BreachedCount;
}

/// <summary>Phase 20 §7: mean resolution time (identical definition to the existing
/// <see cref="ResolutionTimeSummary"/> KPI — <c>ResolvedAt − SlaStartedAt</c>, never <c>CreatedAt</c>)
/// for tickets resolved within the selected range, grouped by <see cref="WorkType"/>. Every work
/// type appears, including one with no qualifying tickets (<see cref="Average"/> null,
/// <see cref="SampleCount"/> zero).</summary>
public sealed record DashboardWorkTypeResolution(WorkType WorkType, TimeSpan? Average, int SampleCount);

/// <summary>
/// First-run workspace setup state (ADR-0020, invite/project semantics revised by ADR-0026) —
/// facts derived live from the caller's own organization plus two persisted skip flags on
/// <see cref="FlowOps.Domain.Organizations.Organization"/> (skipping creates no row of its own, so
/// it cannot be derived like everything else here). "Organization created" is not a field here: it
/// is always true for an authenticated caller (they are necessarily inside one), so the dashboard
/// renders it as a given rather than asking this record to state the obvious.
/// </summary>
/// <param name="HasTeam">The organization has at least one team.</param>
/// <param name="HasSentInvitationOrMember">ADR-0026: the organization has sent at least one
/// invitation (regardless of whether it was ever accepted) OR has more than one active membership.
/// Deliberately reverses ADR-0020's original "must actually accept" rule — the product owner's
/// explicit call — on the reasoning that the Admin's own action (inviting) is what this item
/// should reward, not something outside their control (whether the invitee has gotten to it yet).</param>
/// <param name="InviteStepSkipped">The Admin explicitly skipped this step.</param>
/// <param name="HasProject">The organization has at least one project.</param>
/// <param name="ProjectStepSkipped">The Admin explicitly skipped this step.</param>
/// <param name="HasTicket">The organization has at least one ticket.</param>
public sealed record WorkspaceSetupStatus(
    bool HasTeam,
    bool HasSentInvitationOrMember,
    bool InviteStepSkipped,
    bool HasProject,
    bool ProjectStepSkipped,
    bool HasTicket)
{
    public bool InviteComplete => HasSentInvitationOrMember || InviteStepSkipped;

    public bool ProjectComplete => HasProject || ProjectStepSkipped;

    public bool IsComplete => HasTeam && InviteComplete && ProjectComplete && HasTicket;
}
