// <auto-generated />
using System;
using FlowOps.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowOps.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FlowOpsDbContext))]
    [Migration("20260916082221_AddInvitationTeamId")]
    partial class AddInvitationTeamId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("ticket_reference_seq");

            modelBuilder.Entity("FlowOps.Domain.Catalog.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultWorkType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_work_type");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("TeamId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_team_id_name")
                        .HasFilter("is_active = true");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_categories_default_work_type", "default_work_type IN ('Incident', 'ServiceRequest', 'Task', 'Problem')");
                        });
                });

            modelBuilder.Entity("FlowOps.Domain.Catalog.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_organization_id_name")
                        .HasFilter("is_active = true");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("FlowOps.Domain.Directory.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_organization_id_name")
                        .HasFilter("is_active = true");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("FlowOps.Domain.Directory.TeamMember", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("IsTeamManager")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_team_manager");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.HasKey("TeamId", "UserId")
                        .HasName("pk_team_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_team_members_user_id");

                    b.ToTable("team_members", (string)null);
                });

            modelBuilder.Entity("FlowOps.Domain.Organizations.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invited_email");

                    b.Property<string>("NormalizedInvitedEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_invited_email");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("InvitedByUserId")
                        .HasDatabaseName("ix_invitations_invited_by_user_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_invitations_team_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_invitations_token_hash");

                    b.HasIndex("OrganizationId", "NormalizedInvitedEmail")
                        .HasDatabaseName("ix_invitations_organization_id_normalized_invited_email");

                    b.ToTable("invitations", null, t =>
                        {
                            t.HasCheckConstraint("ck_invitations_role", "role IN ('Admin', 'Manager', 'Agent', 'Viewer')");
                        });
                });

            modelBuilder.Entity("FlowOps.Domain.Organizations.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("InviteStepSkippedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invite_step_skipped_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("ProjectStepSkippedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("project_step_skipped_at");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("FlowOps.Domain.Organizations.OrganizationMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_organization_memberships");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_organization_memberships_user_id");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_organization_memberships_organization_id_user_id");

                    b.ToTable("organization_memberships", (string)null);
                });

            modelBuilder.Entity("FlowOps.Domain.Platform.PlatformAuditEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int?>("TargetOrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("target_organization_id");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id");

                    b.HasKey("Id")
                        .HasName("pk_platform_audit_events");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_platform_audit_events_actor_user_id");

                    b.HasIndex("TargetOrganizationId")
                        .HasDatabaseName("ix_platform_audit_events_target_organization_id");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("ix_platform_audit_events_target_user_id");

                    b.ToTable("platform_audit_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_platform_audit_events_event_type", "event_type IN ('OrganizationDeactivated', 'OrganizationReactivated', 'UserDeactivated', 'UserReactivated', 'UserApproved', 'UserRejected')");

                            t.HasCheckConstraint("ck_platform_audit_events_exactly_one_target", "(target_organization_id IS NOT NULL)::int + (target_user_id IS NOT NULL)::int = 1");
                        });
                });

            modelBuilder.Entity("FlowOps.Domain.Sla.SlaConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<int>("RiskThresholdPercent")
                        .HasColumnType("integer")
                        .HasColumnName("risk_threshold_percent");

                    b.Property<int>("TargetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("target_minutes");

                    b.Property<string>("WorkType")
                        .HasColumnType("text")
                        .HasColumnName("work_type");

                    b.HasKey("Id")
                        .HasName("pk_sla_configurations");

                    b.HasIndex("Priority")
                        .IsUnique()
                        .HasDatabaseName("ix_sla_configurations_default_per_priority")
                        .HasFilter("work_type IS NULL");

                    b.HasIndex("WorkType", "Priority")
                        .IsUnique()
                        .HasDatabaseName("ix_sla_configurations_work_type_priority")
                        .HasFilter("work_type IS NOT NULL");

                    b.ToTable("sla_configurations", null, t =>
                        {
                            t.HasCheckConstraint("ck_sla_configurations_priority", "priority IN ('Low', 'Medium', 'High', 'Critical')");

                            t.HasCheckConstraint("ck_sla_configurations_work_type", "work_type IS NULL OR work_type IN ('Incident', 'ServiceRequest', 'Task', 'Problem')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Priority = "Critical",
                            RiskThresholdPercent = 80,
                            TargetMinutes = 240
                        },
                        new
                        {
                            Id = 2,
                            Priority = "High",
                            RiskThresholdPercent = 80,
                            TargetMinutes = 480
                        },
                        new
                        {
                            Id = 3,
                            Priority = "Medium",
                            RiskThresholdPercent = 80,
                            TargetMinutes = 1440
                        },
                        new
                        {
                            Id = 4,
                            Priority = "Low",
                            RiskThresholdPercent = 80,
                            TargetMinutes = 4320
                        });
                });

            modelBuilder.Entity("FlowOps.Domain.Tickets.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<int>("AssignmentChangeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("assignment_change_count");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("PendingReason")
                        .HasColumnType("text")
                        .HasColumnName("pending_reason");

                    b.Property<DateTimeOffset?>("PendingSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pending_since");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reference")
                        .HasDefaultValueSql("'FO-' || lpad(nextval('ticket_reference_seq')::text, 6, '0')");

                    b.Property<int>("ReopenCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reopen_count");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<string>("ResolutionCode")
                        .HasColumnType("text")
                        .HasColumnName("resolution_code");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<DateTimeOffset>("SlaDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_due_at");

                    b.Property<bool?>("SlaMet")
                        .HasColumnType("boolean")
                        .HasColumnName("sla_met");

                    b.Property<int>("SlaPausedMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sla_paused_minutes");

                    b.Property<DateTimeOffset>("SlaStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_started_at");

                    b.Property<int>("SlaTargetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("sla_target_minutes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("work_type");

                    b.Property<string>("_statusBeforePending")
                        .HasColumnType("text")
                        .HasColumnName("status_before_pending");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_tickets_open_assignee")
                        .HasFilter("status NOT IN ('Resolved', 'Closed')");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_tickets_category_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tickets_open_unassigned")
                        .HasFilter("assignee_id IS NULL AND status NOT IN ('Resolved', 'Closed')");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_tickets_project_id");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_tickets_reference");

                    b.HasIndex("RequesterId")
                        .HasDatabaseName("ix_tickets_requester_id");

                    b.HasIndex("ResolvedAt")
                        .HasDatabaseName("ix_tickets_resolved_at");

                    b.HasIndex("SlaDueAt")
                        .HasDatabaseName("ix_tickets_open_sla_due")
                        .HasFilter("status NOT IN ('Resolved', 'Closed')");

                    b.HasIndex("Title")
                        .HasDatabaseName("gin_tickets_title_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("TeamId", "Priority")
                        .HasDatabaseName("ix_tickets_open_team_priority")
                        .HasFilter("status NOT IN ('Resolved', 'Closed')");

                    b.ToTable("tickets", null, t =>
                        {
                            t.HasCheckConstraint("ck_tickets_closed_at", "status <> 'Closed' OR closed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_tickets_priority", "priority IN ('Low', 'Medium', 'High', 'Critical')");

                            t.HasCheckConstraint("ck_tickets_resolution_code", "resolution_code IS NULL OR resolution_code IN ('Fixed', 'Completed', 'WorkaroundProvided', 'NoFaultFound', 'Duplicate', 'Withdrawn')");

                            t.HasCheckConstraint("ck_tickets_resolution_present", "status NOT IN ('Resolved', 'Closed') OR (resolved_at IS NOT NULL AND resolution_code IS NOT NULL AND resolution_notes IS NOT NULL)");

                            t.HasCheckConstraint("ck_tickets_sla_due_after_started", "sla_due_at > sla_started_at");

                            t.HasCheckConstraint("ck_tickets_status", "status IN ('Open', 'Assigned', 'InProgress', 'Pending', 'Resolved', 'Closed')");

                            t.HasCheckConstraint("ck_tickets_status_before_pending", "status_before_pending IS NULL OR status_before_pending IN ('Open', 'Assigned', 'InProgress', 'Pending', 'Resolved', 'Closed')");

                            t.HasCheckConstraint("ck_tickets_work_type", "work_type IN ('Incident', 'ServiceRequest', 'Task', 'Problem')");
                        });
                });

            modelBuilder.Entity("FlowOps.Domain.Tickets.TicketComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsInternal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_internal");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_comments");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_ticket_comments_author_id");

                    b.HasIndex("TicketId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ticket_comments_ticket");

                    b.ToTable("ticket_comments", (string)null);
                });

            modelBuilder.Entity("FlowOps.Domain.Tickets.TicketEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Field")
                        .HasColumnType("text")
                        .HasColumnName("field");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_events");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_ticket_events_actor_user_id");

                    b.HasIndex("TicketId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ticket_events_ticket");

                    b.ToTable("ticket_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_ticket_events_event_type", "event_type IN ('Created', 'Assigned', 'Reassigned', 'Unassigned', 'StatusChanged', 'PriorityChanged', 'CategoryChanged', 'TeamChanged', 'DueDateChanged', 'SlaRecalculated', 'PutOnHold', 'Resumed', 'Resolved', 'Reopened', 'Closed', 'CommentAdded')");
                        });
                });

            modelBuilder.Entity("FlowOps.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000a1"),
                            ConcurrencyStamp = "00000000-0000-0000-0000-1000000000a1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000a2"),
                            ConcurrencyStamp = "00000000-0000-0000-0000-1000000000a2",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000a3"),
                            ConcurrencyStamp = "00000000-0000-0000-0000-1000000000a3",
                            Name = "Agent",
                            NormalizedName = "AGENT"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000a4"),
                            ConcurrencyStamp = "00000000-0000-0000-0000-1000000000a4",
                            Name = "Viewer",
                            NormalizedName = "VIEWER"
                        });
                });

            modelBuilder.Entity("FlowOps.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDemoProtected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_demo_protected");

                    b.Property<bool>("IsPlatformAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_platform_admin");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text")
                        .HasColumnName("job_title");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<int?>("PrimaryTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("primary_team_id");

                    b.Property<DateTimeOffset?>("RegistrationApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_approved_at");

                    b.Property<DateTimeOffset?>("RegistrationRejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_rejected_at");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PrimaryTeamId")
                        .HasDatabaseName("ix_asp_net_users_primary_team_id");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FlowOps.Domain.Catalog.Category", b =>
                {
                    b.HasOne("FlowOps.Domain.Directory.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_categories_teams_team_id");
                });

            modelBuilder.Entity("FlowOps.Domain.Catalog.Project", b =>
                {
                    b.HasOne("FlowOps.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_organizations_organization_id");
                });

            modelBuilder.Entity("FlowOps.Domain.Directory.Team", b =>
                {
                    b.HasOne("FlowOps.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teams_organizations_organization_id");
                });

            modelBuilder.Entity("FlowOps.Domain.Directory.TeamMember", b =>
                {
                    b.HasOne("FlowOps.Domain.Directory.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_members_teams_team_id");

                    b.HasOne("FlowOps.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_members_asp_net_users_user_id");
                });

            modelBuilder.Entity("FlowOps.Domain.Organizations.Invitation", b =>
                {
                    b.HasOne("FlowOps.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_asp_net_users_invited_by_user_id");

                    b.HasOne("FlowOps.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_organizations_organization_id");

                    b.HasOne("FlowOps.Domain.Directory.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_invitations_teams_team_id");
                });

            modelBuilder.Entity("FlowOps.Domain.Organizations.OrganizationMembership", b =>
                {
                    b.HasOne("FlowOps.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_memberships_organizations_organization_id");

                    b.HasOne("FlowOps.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_memberships_asp_net_users_user_id");
                });

            modelBuilder.Entity("FlowOps.Domain.Platform.PlatformAuditEvent", b =>
                {
                    b.HasOne("FlowOps.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_platform_audit_events_asp_net_users_actor_user_id");

                    b.HasOne("FlowOps.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("TargetOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_platform_audit_events_organizations_target_organization_id");

                    b.HasOne("FlowOps.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_platform_audit_events_asp_net_users_target_user_id");
                });

            modelBuilder.Entity("FlowOps.Domain.Tickets.Ticket", b =>
                {
                    b.HasOne("FlowOps.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tickets_asp_net_users_assignee_id");

                    b.HasOne("FlowOps.Domain.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_categories_category_id");

                    b.HasOne("FlowOps.Domain.Catalog.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tickets_projects_project_id");

                    b.HasOne("FlowOps.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_asp_net_users_requester_id");

                    b.HasOne("FlowOps.Domain.Directory.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_teams_team_id");
                });

            modelBuilder.Entity("FlowOps.Domain.Tickets.TicketComment", b =>
                {
                    b.HasOne("FlowOps.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_comments_asp_net_users_author_id");

                    b.HasOne("FlowOps.Domain.Tickets.Ticket", null)
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_comments_tickets_ticket_id");
                });

            modelBuilder.Entity("FlowOps.Domain.Tickets.TicketEvent", b =>
                {
                    b.HasOne("FlowOps.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_events_asp_net_users_actor_user_id");

                    b.HasOne("FlowOps.Domain.Tickets.Ticket", null)
                        .WithMany("Events")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_events_tickets_ticket_id");
                });

            modelBuilder.Entity("FlowOps.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.HasOne("FlowOps.Domain.Directory.Team", null)
                        .WithMany()
                        .HasForeignKey("PrimaryTeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_asp_net_users_teams_primary_team_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("FlowOps.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FlowOps.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FlowOps.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("FlowOps.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("FlowOps.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FlowOps.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("FlowOps.Domain.Tickets.Ticket", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
