// <auto-generated />
using System;
using FlowOps.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowOps.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FlowOpsDbContext))]
    [Migration("20260910021509_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("ticket_reference_seq");

            modelBuilder.Entity("FlowOps.Domain.Catalog.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultWorkType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_work_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("TeamId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_team_id_name");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_categories_default_work_type", "default_work_type IN ('Incident', 'ServiceRequest', 'Task', 'Problem')");
                        });
                });

            modelBuilder.Entity("FlowOps.Domain.Catalog.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_name");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("FlowOps.Domain.Directory.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_name");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("FlowOps.Domain.Directory.TeamMember", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("IsTeamManager")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_team_manager");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.HasKey("TeamId", "UserId")
                        .HasName("pk_team_members");

                    b.ToTable("team_members", (string)null);
                });

            modelBuilder.Entity("FlowOps.Domain.Sla.SlaConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<int>("RiskThresholdPercent")
                        .HasColumnType("integer")
                        .HasColumnName("risk_threshold_percent");

                    b.Property<int>("TargetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("target_minutes");

                    b.Property<string>("WorkType")
                        .HasColumnType("text")
                        .HasColumnName("work_type");

                    b.HasKey("Id")
                        .HasName("pk_sla_configurations");

                    b.HasIndex("Priority")
                        .IsUnique()
                        .HasDatabaseName("ix_sla_configurations_default_per_priority")
                        .HasFilter("work_type IS NULL");

                    b.HasIndex("WorkType", "Priority")
                        .IsUnique()
                        .HasDatabaseName("ix_sla_configurations_work_type_priority")
                        .HasFilter("work_type IS NOT NULL");

                    b.ToTable("sla_configurations", null, t =>
                        {
                            t.HasCheckConstraint("ck_sla_configurations_priority", "priority IN ('Low', 'Medium', 'High', 'Critical')");

                            t.HasCheckConstraint("ck_sla_configurations_work_type", "work_type IS NULL OR work_type IN ('Incident', 'ServiceRequest', 'Task', 'Problem')");
                        });
                });

            modelBuilder.Entity("FlowOps.Domain.Tickets.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<int>("AssignmentChangeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("assignment_change_count");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("PendingReason")
                        .HasColumnType("text")
                        .HasColumnName("pending_reason");

                    b.Property<DateTimeOffset?>("PendingSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pending_since");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reference")
                        .HasDefaultValueSql("'FO-' || lpad(nextval('ticket_reference_seq')::text, 6, '0')");

                    b.Property<int>("ReopenCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reopen_count");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<string>("ResolutionCode")
                        .HasColumnType("text")
                        .HasColumnName("resolution_code");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<DateTimeOffset>("SlaDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_due_at");

                    b.Property<bool?>("SlaMet")
                        .HasColumnType("boolean")
                        .HasColumnName("sla_met");

                    b.Property<int>("SlaPausedMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sla_paused_minutes");

                    b.Property<DateTimeOffset>("SlaStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_started_at");

                    b.Property<int>("SlaTargetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("sla_target_minutes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("work_type");

                    b.Property<string>("_statusBeforePending")
                        .HasColumnType("text")
                        .HasColumnName("status_before_pending");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_tickets_open_assignee")
                        .HasFilter("status NOT IN ('Resolved', 'Closed')");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_tickets_category_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tickets_open_unassigned")
                        .HasFilter("assignee_id IS NULL AND status NOT IN ('Resolved', 'Closed')");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_tickets_project_id");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_tickets_reference");

                    b.HasIndex("ResolvedAt")
                        .HasDatabaseName("ix_tickets_resolved_at");

                    b.HasIndex("SlaDueAt")
                        .HasDatabaseName("ix_tickets_open_sla_due")
                        .HasFilter("status NOT IN ('Resolved', 'Closed')");

                    b.HasIndex("Title")
                        .HasDatabaseName("gin_tickets_title_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("TeamId", "Priority")
                        .HasDatabaseName("ix_tickets_open_team_priority")
                        .HasFilter("status NOT IN ('Resolved', 'Closed')");

                    b.ToTable("tickets", null, t =>
                        {
                            t.HasCheckConstraint("ck_tickets_closed_at", "status <> 'Closed' OR closed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_tickets_priority", "priority IN ('Low', 'Medium', 'High', 'Critical')");

                            t.HasCheckConstraint("ck_tickets_resolution_code", "resolution_code IS NULL OR resolution_code IN ('Fixed', 'Completed', 'WorkaroundProvided', 'NoFaultFound', 'Duplicate', 'Withdrawn')");

                            t.HasCheckConstraint("ck_tickets_resolution_present", "status NOT IN ('Resolved', 'Closed') OR (resolved_at IS NOT NULL AND resolution_code IS NOT NULL AND resolution_notes IS NOT NULL)");

                            t.HasCheckConstraint("ck_tickets_sla_due_after_started", "sla_due_at > sla_started_at");

                            t.HasCheckConstraint("ck_tickets_status", "status IN ('Open', 'Assigned', 'InProgress', 'Pending', 'Resolved', 'Closed')");

                            t.HasCheckConstraint("ck_tickets_status_before_pending", "status_before_pending IS NULL OR status_before_pending IN ('Open', 'Assigned', 'InProgress', 'Pending', 'Resolved', 'Closed')");

                            t.HasCheckConstraint("ck_tickets_work_type", "work_type IN ('Incident', 'ServiceRequest', 'Task', 'Problem')");
                        });
                });

            modelBuilder.Entity("FlowOps.Domain.Tickets.TicketComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsInternal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_internal");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_comments");

                    b.HasIndex("TicketId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ticket_comments_ticket");

                    b.ToTable("ticket_comments", (string)null);
                });

            modelBuilder.Entity("FlowOps.Domain.Tickets.TicketEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("Field")
                        .HasColumnType("text")
                        .HasColumnName("field");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_events");

                    b.HasIndex("TicketId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ticket_events_ticket");

                    b.ToTable("ticket_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_ticket_events_event_type", "event_type IN ('Created', 'Assigned', 'Reassigned', 'Unassigned', 'StatusChanged', 'PriorityChanged', 'CategoryChanged', 'TeamChanged', 'DueDateChanged', 'SlaRecalculated', 'PutOnHold', 'Resumed', 'Resolved', 'Reopened', 'Closed', 'CommentAdded')");
                        });
                });

            modelBuilder.Entity("FlowOps.Domain.Catalog.Category", b =>
                {
                    b.HasOne("FlowOps.Domain.Directory.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_categories_teams_team_id");
                });

            modelBuilder.Entity("FlowOps.Domain.Directory.TeamMember", b =>
                {
                    b.HasOne("FlowOps.Domain.Directory.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_members_teams_team_id");
                });

            modelBuilder.Entity("FlowOps.Domain.Tickets.Ticket", b =>
                {
                    b.HasOne("FlowOps.Domain.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_categories_category_id");

                    b.HasOne("FlowOps.Domain.Catalog.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tickets_projects_project_id");

                    b.HasOne("FlowOps.Domain.Directory.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_teams_team_id");
                });

            modelBuilder.Entity("FlowOps.Domain.Tickets.TicketComment", b =>
                {
                    b.HasOne("FlowOps.Domain.Tickets.Ticket", null)
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_comments_tickets_ticket_id");
                });

            modelBuilder.Entity("FlowOps.Domain.Tickets.TicketEvent", b =>
                {
                    b.HasOne("FlowOps.Domain.Tickets.Ticket", null)
                        .WithMany("Events")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_events_tickets_ticket_id");
                });

            modelBuilder.Entity("FlowOps.Domain.Tickets.Ticket", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
